@tool
extends EditorScenePostImport
##
## Builds physics bodies and collision shapes from metadata authored in Blender.
##
## Generated by the Blender "Godot Pipeline" add-on. Point a scene's
## Import > Import Script at this file (the add-on can do it for you).
##
## The add-on writes Blender custom properties, the glTF exporter turns them
## into `extras`, and Godot exposes them as `node.get_meta("extras")`. Nothing
## in the stock importer acts on that metadata, which is what this script is
## for. It runs after meshes are generated, so every node here is a real
## MeshInstance3D with a real Mesh.
##
## Blender Z-up becomes Godot Y-up on export, so capsules and cylinders
## authored standing along Blender's Z arrive standing along Godot's Y, which
## is the axis CapsuleShape3D and CylinderShape3D use.

const KEY_BODY := "godot_body"
const KEY_SHAPE := "godot_shape"
const KEY_MARGIN := "godot_shape_margin"
const KEY_VISUAL := "godot_shape_visual"
const KEY_LAYER := "godot_collision_layer"
const KEY_MASK := "godot_collision_mask"
const KEY_MASS := "godot_mass"
const KEY_PRIORITY := "godot_collision_priority"

const PRIMITIVES := {
	"BoxShape3D": true,
	"SphereShape3D": true,
	"CapsuleShape3D": true,
	"CylinderShape3D": true,
}


func _post_import(scene: Node) -> Object:
	var bodies := _build_bodies(scene)
	var shapes := _build_shapes(scene)
	if bodies > 0 or shapes > 0:
		_reown(scene, scene)
		print("[godot_pipeline] %s: %d body(ies), %d shape(s)" % [
			get_source_file().get_file(), bodies, shapes])
	return scene


# -- traversal --------------------------------------------------------------

## Depth-first snapshot of the tree. The return type is spelled out because
## callers rely on the loop variable being a Node for type inference.
func _flatten(node: Node) -> Array[Node]:
	var out: Array[Node] = [node]
	for child in node.get_children():
		out.append_array(_flatten(child))
	return out


func _extras(node: Node) -> Dictionary:
	if node.has_meta("extras"):
		var value: Variant = node.get_meta("extras")
		if value is Dictionary:
			return value
	return {}


func _reown(node: Node, scene_owner: Node) -> void:
	for child in node.get_children():
		child.owner = scene_owner
		_reown(child, scene_owner)


# -- bodies -----------------------------------------------------------------

func _new_body(type_name: String) -> CollisionObject3D:
	match type_name:
		"StaticBody3D": return StaticBody3D.new()
		"AnimatableBody3D": return AnimatableBody3D.new()
		"RigidBody3D": return RigidBody3D.new()
		"CharacterBody3D": return CharacterBody3D.new()
		"Area3D": return Area3D.new()
		"VehicleBody3D": return VehicleBody3D.new()
	push_warning("[godot_pipeline] unknown body type '%s'" % type_name)
	return null


func _configure_body(body: CollisionObject3D, extras: Dictionary) -> void:
	if extras.has(KEY_LAYER):
		body.collision_layer = int(extras[KEY_LAYER])
	if extras.has(KEY_MASK):
		body.collision_mask = int(extras[KEY_MASK])
	if extras.has(KEY_PRIORITY):
		body.collision_priority = float(extras[KEY_PRIORITY])
	if body is RigidBody3D and extras.has(KEY_MASS):
		(body as RigidBody3D).mass = float(extras[KEY_MASS])


func _build_bodies(scene: Node) -> int:
	var count := 0
	for node in _flatten(scene):
		var extras := _extras(node)
		if not extras.has(KEY_BODY):
			continue
		var node3d := node as Node3D
		if node3d == null:
			continue
		if node == scene:
			push_warning("[godot_pipeline] '%s' is the scene root; set the root type in the "
				% node.name + "import options instead of tagging it in Blender")
			continue

		var body := _new_body(String(extras[KEY_BODY]))
		if body == null:
			continue
		_configure_body(body, extras)

		# Mirrors what the stock importer does for -rigid: the body takes the
		# node's place and its transform, and the mesh becomes its child. Any
		# collision proxies parented under the node in Blender move up to the
		# body, which is exactly where CollisionShape3D has to live.
		var original_name := String(node.name)
		node.name = original_name + "_mesh"
		body.name = original_name

		var local := node3d.transform
		node.replace_by(body)
		body.transform = local
		node3d.transform = Transform3D.IDENTITY
		body.add_child(node)
		count += 1
	return count


func _find_body(node: Node) -> CollisionObject3D:
	var current := node.get_parent()
	while current != null:
		if current is CollisionObject3D:
			return current as CollisionObject3D
		current = current.get_parent()
	return null


func _wrap_in_static_body(node: Node3D) -> CollisionObject3D:
	var parent := node.get_parent()
	if parent == null:
		return null
	var body := StaticBody3D.new()
	body.name = "StaticBody3D"
	parent.add_child(body)
	push_warning("[godot_pipeline] '%s' has a collision shape but no body above it; " % node.name
		+ "added a StaticBody3D. Set a Body on its parent in Blender to control the type.")
	return body


# -- shapes -----------------------------------------------------------------

## Transform of `node` expressed in `body`'s local space.
##
## Node3D.global_transform is unusable here: during import the scene is a
## detached node tree, so the transform is accumulated by hand instead.
func _transform_between(node: Node3D, body: CollisionObject3D) -> Transform3D:
	var stop := body.get_parent()
	var xform := Transform3D.IDENTITY
	var current: Node3D = node
	while current != null and current != stop:
		xform = current.transform * xform
		current = current.get_parent() as Node3D
	return body.transform.affine_inverse() * xform


func _primitive_shape(type_name: String, size: Vector3) -> Shape3D:
	match type_name:
		"BoxShape3D":
			var box := BoxShape3D.new()
			box.size = size
			return box
		"SphereShape3D":
			var sphere := SphereShape3D.new()
			sphere.radius = maxf(maxf(size.x, size.y), size.z) * 0.5
			return sphere
		"CapsuleShape3D":
			var capsule := CapsuleShape3D.new()
			capsule.radius = maxf(size.x, size.z) * 0.5
			# CapsuleShape3D.height is the total height, caps included.
			capsule.height = maxf(size.y, capsule.radius * 2.0)
			return capsule
		"CylinderShape3D":
			var cylinder := CylinderShape3D.new()
			cylinder.radius = maxf(size.x, size.z) * 0.5
			cylinder.height = size.y
			return cylinder
	return null


func _make_collision_shape(node: Node3D, extras: Dictionary,
		body: CollisionObject3D) -> CollisionShape3D:
	var type_name := String(extras[KEY_SHAPE])
	var mesh_instance := node as MeshInstance3D
	var mesh: Mesh = mesh_instance.mesh if mesh_instance != null else null
	if mesh == null:
		push_warning("[godot_pipeline] '%s' is tagged %s but carries no mesh"
			% [node.name, type_name])
		return null

	var xform := _transform_between(node, body)
	var shape: Shape3D = null
	var placement := xform

	if PRIMITIVES.has(type_name):
		# Bake the node's scale into the shape's dimensions and hand the
		# CollisionShape3D an unscaled basis: Godot misbehaves on collision
		# nodes with non-uniform scale.
		var aabb := mesh.get_aabb()
		var scale := xform.basis.get_scale()
		shape = _primitive_shape(type_name, aabb.size * scale)
		placement = Transform3D(xform.basis.orthonormalized(), xform * aabb.get_center())
	elif type_name == "ConvexPolygonShape3D":
		shape = mesh.create_convex_shape()
	elif type_name == "ConcavePolygonShape3D":
		shape = mesh.create_trimesh_shape()
	else:
		push_warning("[godot_pipeline] unknown shape type '%s'" % type_name)
		return null

	if shape == null:
		push_warning("[godot_pipeline] could not build %s for '%s'" % [type_name, node.name])
		return null

	if extras.has(KEY_MARGIN):
		shape.margin = float(extras[KEY_MARGIN])

	var collision := CollisionShape3D.new()
	# A bare proxy hands its name over; a node that keeps its mesh would
	# otherwise collide with the MeshInstance3D still sitting next to it.
	collision.name = String(node.name)
	if bool(extras.get(KEY_VISUAL, false)):
		collision.name = String(node.name) + "_shape"
	collision.shape = shape
	collision.transform = placement
	return collision


func _build_shapes(scene: Node) -> int:
	var count := 0
	for node in _flatten(scene):
		var extras := _extras(node)
		if not extras.has(KEY_SHAPE):
			continue
		var node3d := node as Node3D
		if node3d == null:
			continue

		var body := _find_body(node)
		if body == null:
			body = _wrap_in_static_body(node3d)
			if body == null:
				continue

		var collision := _make_collision_shape(node3d, extras, body)
		if collision == null:
			continue

		# Retire the proxy *before* adding the shape. Adding it first would put
		# two siblings with the same name under the body, and Godot would
		# silently rename the shape to something like @CollisionShape3D@19799 -
		# a name that changes on every reimport and breaks any NodePath.
		if not bool(extras.get(KEY_VISUAL, false)):
			var parent := node.get_parent()
			if parent != null:
				parent.remove_child(node)
			node.free()

		body.add_child(collision)
		count += 1
	return count
